package c2sptlog

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"os"
	"strings"
	"testing"
	"time"

	dnsid "github.com/dnsid-ai/dnsid-go"
)

// TestTrustEpochVectors checks that the checked-in shared vector file is
// exactly what the generator produces, then runs every case from the file
// alone through the same verifier wiring NewVerificationRegistry builds.
func TestTrustEpochVectors(t *testing.T) {
	var generated bytes.Buffer
	enc := json.NewEncoder(&generated)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(buildTrustEpochVectors(t)); err != nil {
		t.Fatal(err)
	}
	if os.Getenv("DNSID_UPDATE_TRUST_EPOCH_VECTORS") == "1" {
		if err := os.WriteFile(trustEpochVectorPath, generated.Bytes(), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	data, err := os.ReadFile(trustEpochVectorPath)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(data, generated.Bytes()) {
		t.Fatalf("%s is stale; regenerate with DNSID_UPDATE_TRUST_EPOCH_VECTORS=1 go test -run TestTrustEpochVectors ./log/c2sptlog", trustEpochVectorPath)
	}

	var vectors epochVectorFile
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&vectors); err != nil {
		t.Fatal(err)
	}
	if vectors.Format != trustEpochVectorFormat {
		t.Fatalf("format = %q", vectors.Format)
	}
	requireEpochVectorCoverage(t, vectors)
	p := vectors.Parameters
	now := func() time.Time { return time.Unix(p.Now, 0).UTC() }

	for _, tc := range vectors.ProfileCases {
		t.Run("profile/"+tc.Name, func(t *testing.T) {
			profile, err := ParseTrustProfile([]byte(tc.Document))
			if tc.Expect.Result == "reject" {
				var parseErr *dnsid.ParseError
				if !errors.As(err, &parseErr) {
					t.Fatalf("error = %v, want profile_invalid", err)
				}
				return
			}
			if err != nil {
				t.Fatalf("ParseTrustProfile: %v", err)
			}
			epochs, err := profile.TrustEpochs()
			if err != nil {
				t.Fatal(err)
			}
			var ids []string
			for _, epoch := range epochs {
				ids = append(ids, epoch.ID)
			}
			if strings.Join(ids, ",") != strings.Join(tc.EpochIDs, ",") || len(ids) != len(tc.EpochIDs) {
				t.Fatalf("epoch ids = %q, want %q", ids, tc.EpochIDs)
			}
		})
	}

	for _, tc := range vectors.CheckpointCases {
		t.Run("checkpoint/"+tc.Name, func(t *testing.T) {
			client, _ := epochVectorClient(t, vectors, tc.Profile, now)
			verified, err := client.policy.verifyCheckpoint(client.ref, []byte(tc.Checkpoint))
			if err == nil && verified.Checkpoint.Size != tc.TreeSize {
				t.Fatalf("size = %d, want %d", verified.Checkpoint.Size, tc.TreeSize)
			}
			checkEpochExpectation(t, tc.Expect, err, func() string { return verified.TrustEpoch })
		})
	}

	for _, tc := range vectors.BundleCases {
		t.Run("bundle/"+tc.Name, func(t *testing.T) {
			client, _ := epochVectorClient(t, vectors, tc.Profile, now)
			source, ok := client.source.(*fetchedStreamBundleSource)
			if !ok {
				t.Fatalf("source = %T, want bundle source", client.source)
			}
			trust := source.trust
			trust.Now = now
			trust.TrustedCheckpointStore = nil
			verified, err := VerifyStreamBundle(context.Background(), []byte(tc.Bundle), trust)
			checkEpochExpectation(t, tc.Expect, err, func() string { return verified.TrustEpoch })
		})
	}

	for _, tc := range vectors.ContinuityCases {
		t.Run("continuity/"+tc.Name, func(t *testing.T) {
			client, store := epochVectorClient(t, vectors, tc.Profile, now)
			for i, step := range tc.Steps {
				var hashes [][]byte
				for _, encoded := range step.ConsistencyProof {
					hash, err := base64.StdEncoding.DecodeString(encoded)
					if err != nil {
						t.Fatal(err)
					}
					hashes = append(hashes, hash)
				}
				client.source = checkpointProofSource{hashes: hashes}
				verified, err := client.policy.verifyCheckpoint(client.ref, []byte(step.Checkpoint))
				if err == nil {
					err = client.advanceTrustedCheckpoint(context.Background(), TrustedC2spCheckpoint{
						Origin:      verified.Checkpoint.Origin,
						TreeSize:    verified.Checkpoint.Size,
						RootHash:    append([]byte(nil), verified.Checkpoint.Hash...),
						WitnessTime: verified.CheckpointWitnessTime,
					})
				}
				checkEpochExpectation(t, step.Expect, err, func() string { return verified.TrustEpoch })
				trusted, err := store.Load(p.Origin)
				if err != nil {
					t.Fatal(err)
				}
				switch {
				case step.TrustedAfter == nil && trusted != nil:
					t.Fatalf("step %d: trusted state = %+v, want none", i, trusted)
				case step.TrustedAfter != nil && (trusted == nil || trusted.TreeSize != step.TrustedAfter.TreeSize || base64.StdEncoding.EncodeToString(trusted.RootHash) != step.TrustedAfter.RootHash):
					t.Fatalf("step %d: trusted state = %+v, want %+v", i, trusted, step.TrustedAfter)
				}
			}
		})
	}
}

// epochVectorClient builds the reader NewVerificationRegistry installs for a
// vector profile, with the vector's freshness and clock.
func epochVectorClient(t *testing.T, vectors epochVectorFile, name string, now func() time.Time) (*Client, TrustedC2spCheckpointStore) {
	t.Helper()
	document, ok := vectors.Profiles[name]
	if !ok {
		t.Fatalf("unknown profile %q", name)
	}
	profile, err := ParseTrustProfile([]byte(document))
	if err != nil {
		t.Fatalf("ParseTrustProfile(%s): %v", name, err)
	}
	store := NewMemoryTrustedC2spCheckpointStore()
	p := vectors.Parameters
	registry, err := NewVerificationRegistry(context.Background(), VerificationRegistryConfig{
		TrustProfile:           &profile,
		ResourceFetcher:        &testBoundedFetcher{},
		TrustedCheckpointStore: store,
		CheckpointMaxAge:       time.Duration(p.CheckpointMaxAgeSeconds) * time.Second,
		AllowedClockSkew:       time.Duration(p.ClockSkewSeconds) * time.Second,
		MaxBundleLifetime:      time.Duration(p.MaxBundleLifetimeSeconds) * time.Second,
	})
	if err != nil {
		t.Fatalf("NewVerificationRegistry(%s): %v", name, err)
	}
	client := verificationClient(t, registry, p.LR)
	client.policy.Now = now
	return client, store
}

// epochVectorReason maps a Go error to the vector's language-neutral reason.
func epochVectorReason(err error) string {
	var advance *CheckpointAdvanceError
	if errors.As(err, &advance) {
		return string(advance.Kind)
	}
	message := err.Error()
	for _, reason := range []struct{ code, text string }{
		{"bundle_signer", "signer is not accepted"},
		{"policy_hash", "policy hash mismatch"},
		{"max_tree_size", "above trust epoch"},
		{"min_tree_size", "below trust epoch"},
		{"witness_quorum", "witness quorum not satisfied"},
		{"stale", "checkpoint is stale"},
		{"log_signature", "verifying c2sp-tlog checkpoint"},
	} {
		if strings.Contains(message, reason.text) {
			return reason.code
		}
	}
	return "unclassified: " + message
}

func checkEpochExpectation(t *testing.T, expect epochExpect, err error, epoch func() string) {
	t.Helper()
	switch expect.Result {
	case "accept":
		if err != nil {
			t.Fatalf("rejected (%s), want accept", epochVectorReason(err))
		}
		if expect.Epoch == nil || epoch() != *expect.Epoch {
			t.Fatalf("accepted under epoch %q, want %v", epoch(), expect.Epoch)
		}
	case "reject":
		if err == nil {
			t.Fatalf("accepted, want reject %s", expect.Reason)
		}
		if got := epochVectorReason(err); got != expect.Reason {
			t.Fatalf("reason = %s, want %s (%v)", got, expect.Reason, err)
		}
	default:
		t.Fatalf("unknown result %q", expect.Result)
	}
}

// requireEpochVectorCoverage pins the cases the T7-6 runbook step and the
// ports depend on, so they cannot silently drop out of the file.
func requireEpochVectorCoverage(t *testing.T, vectors epochVectorFile) {
	t.Helper()
	names := map[string]bool{}
	for _, tc := range vectors.CheckpointCases {
		names[tc.Name] = true
	}
	for _, tc := range vectors.BundleCases {
		names[tc.Name] = true
	}
	for _, tc := range vectors.ContinuityCases {
		names[tc.Name] = true
	}
	for _, tc := range vectors.ProfileCases {
		names["profile/"+tc.Name] = true
	}
	for _, name := range []string{
		"t7-6-legacy-below-n", "t7-6-legacy-at-n", "t7-6-successor-at-n", "t7-6-successor-above-n",
		"t7-6-legacy-above-n-capped", "t7-6-successor-below-n-floored",
		"mix-legacy-log-successor-witness", "mix-successor-log-legacy-witness",
		"bundle-legacy-epoch-at-n", "bundle-successor-epoch-above-n", "bundle-policy-hash-mismatch",
		"v1-legacy-at-n", "v1-bundle-legacy", "profile/v1-legacy",
		"continuity-equal-root-at-n", "continuity-advance-to-n-plus-k",
		"bundle-shared-kid-selects-legacy", "bundle-shared-kid-selects-successor", "bundle-shared-kid-policy-hash-mismatch",
		"forged-legacy-line-successor-accepts", "forged-legacy-line-precedence",
		"profile/max-tree-size-decimal-point", "profile/max-tree-size-exponent", "profile/max-tree-size-boolean",
		"profile/max-tree-size-string", "profile/unsafe-max-tree-size", "profile/max-tree-size-largest",
	} {
		if !names[name] {
			t.Errorf("vector file is missing required case %q", name)
		}
	}
}
